import type { TimelineEvent, TimelineYear, Project, StackCategory } from './types';

export const TIMELINE: TimelineEvent[] = [
  {
    id: 'first-line',
    date: { ru: 'Начало 2024', en: 'Early 2024' },
    year: 2024,
    title: { ru: 'Первая строка кода в проде', en: 'First line in production' },
    description: {
      ru: 'Начал писать на Next.js и NestJS — пет-проекты переросли в реальные задачи. Понял, что фронт и бэк по отдельности — скучно, и пошёл в фуллстек.',
      en: 'Started writing Next.js and NestJS — pet projects grew into real work. Realized frontend and backend in isolation is boring and went fullstack.',
    },
    tag: { ru: 'Старт', en: 'Start' },
    kind: 'milestone',
    role: { ru: 'Старт пути', en: 'Where it started' },
    note: { ru: 'fullstack', en: 'fullstack' },
    stack: ['Next.js', 'NestJS', 'TypeScript'],
  },
  {
    id: 'leepy',
    date: { ru: 'Зима 2024/25', en: 'Winter 2024/25' },
    year: 2025,
    title: { ru: 'Leepy', en: 'Leepy' },
    description: {
      ru: 'Сайт для дизайнера на Next.js + Strapi. Первое серьёзное знакомство с Framer Motion и CMS-архитектурой.',
      en: 'Designer landing on Next.js + Strapi. First deep dive into Framer Motion and CMS architecture.',
    },
    tag: { ru: 'Проект', en: 'Project' },
    kind: 'project',
    status: 'launched',
    role: { ru: 'Frontend Dev', en: 'Frontend Dev' },
    note: { ru: 'запущен', en: 'launched' },
    url: 'https://leepy.ru/',
    stack: ['Next.js', 'Strapi', 'Framer Motion'],
  },
  {
    id: 'lisavi',
    date: { ru: 'Зима 2024/25', en: 'Winter 2024/25' },
    year: 2025,
    title: { ru: 'Lisavi.art', en: 'Lisavi.art' },
    description: {
      ru: 'Запустил e-commerce с нуля: ЮКасса, Т-Банк, доставка с расчётом, промокоды, кастомная админ-панель. Здесь научился держать в голове всю систему.',
      en: 'Built e-commerce from scratch: ЮKassa, T-Bank, shipping calc, promo codes, custom admin panel. Learned to hold an entire system in my head.',
    },
    tag: { ru: 'Проект', en: 'Project' },
    kind: 'project',
    status: 'production',
    role: { ru: 'Fullstack Dev', en: 'Fullstack Dev' },
    note: { ru: 'в проде', en: 'launched' },
    url: 'https://lisavi.ru/',
    stack: ['Next.js', 'NestJS', 'Prisma', 'ЮКасса', 'Т-Банк'],
  },
  {
    id: 'devops-dive',
    date: { ru: 'Зима 2024/25', en: 'Winter 2024/25' },
    year: 2025,
    title: { ru: 'Погружение в DevOps', en: 'DevOps deep dive' },
    description: {
      ru: 'Docker, Nginx, GitHub Actions, VPS. Перестал бояться сервера и научился деплоить без боли.',
      en: 'Docker, Nginx, GitHub Actions, VPS. Stopped being scared of servers and learned to deploy without pain.',
    },
    tag: { ru: 'Скилл', en: 'Skill' },
    kind: 'learn',
    role: { ru: 'Self-taught', en: 'Self-taught' },
    note: { ru: 'скилл', en: 'skill up' },
    stack: ['Docker', 'Nginx', 'GitHub Actions', 'VPS'],
  },
  {
    id: 'istok',
    date: { ru: 'Весна 2025', en: 'Spring 2025' },
    year: 2025,
    title: { ru: 'ИСТОК @ МФТИ', en: 'ИСТОК @ MIPT' },
    description: {
      ru: 'Языковое тестирование для студентов МФТИ. Реализовал автоматическую проверку через GigaChat с кастомным промптом. На платформе уже больше 10 000 тестов.',
      en: 'Language testing platform for MIPT students. Built auto-grading via GigaChat with a custom system prompt. 10K+ tests on the platform.',
    },
    tag: { ru: 'Проект', en: 'Project' },
    kind: 'project',
    status: 'production',
    role: { ru: 'Fullstack Dev', en: 'Fullstack Dev' },
    note: { ru: 'в проде / 10K+ тестов', en: 'in production / 10K+ tests' },
    url: 'https://istok-demo.ru/',
    stack: ['NestJS', 'Next.js', 'GigaChat', 'GigaChain', 'Prisma'],
  },
  {
    id: 'pifagorum',
    date: { ru: 'Лето 2025', en: 'Summer 2025' },
    year: 2025,
    title: { ru: 'Пифагорум', en: 'Пифагорум' },
    description: {
      ru: 'Спроектировал и поднял модуль видеоконференций на LiveKit — от медиасервера до кастомного UI с управлением комнатами и участниками.',
      en: 'Designed and built a video-conference module on LiveKit — from media server to custom UI with room and participant management.',
    },
    tag: { ru: 'Проект', en: 'Project' },
    kind: 'project',
    status: 'production',
    role: { ru: 'Fullstack Dev', en: 'Fullstack Dev' },
    note: { ru: 'в проде', en: 'in production' },
    url: 'https://vc.pifagorum.qque-dev.ru/',
    stack: ['NestJS', 'Next.js', 'GraphQL', 'Prisma', 'LiveKit', 'tldraw'],
  },
  {
    id: 'exploo',
    date: { ru: 'Осень 2025', en: 'Autumn 2025' },
    year: 2025,
    title: { ru: 'Exploo', en: 'Exploo' },
    description: {
      ru: 'Платформа для репетиторов: интерактивные доски (tldraw), расписание, видеосвязь (LiveKit). Hono + tRPC + TanStack, авторизация через Better Auth с привязкой Telegram. Соло-стартап — рос как архитектор.',
      en: 'Tutor platform: interactive whiteboards (tldraw), scheduling, video calls (LiveKit). Hono + tRPC + TanStack, Better Auth with Telegram binding. Solo-founded startup — grew as an architect.',
    },
    tag: { ru: 'Стартап', en: 'Startup' },
    kind: 'work',
    status: 'in-progress',
    role: { ru: 'Solo Founder', en: 'Solo Founder' },
    note: { ru: 'MVP / в работе', en: 'MVP / in progress' },
    url: 'https://exploo.ru',
    stack: ['React', 'Hono', 'tRPC', 'tldraw', 'LiveKit', 'Better Auth'],
  },
  {
    id: 'lofty',
    date: { ru: 'Начало 2026', en: 'Early 2026' },
    year: 2026,
    title: { ru: 'Lofty', en: 'Lofty' },
    description: {
      ru: 'Self-hosted платформа лояльности и учёта для малого бизнеса (кафе, салоны, барбершопы). Уровни с кэшбэком, QR-транзакции, склад, аналитика, white-label — данные на своём сервере, без подписок. Монорепо на Turborepo, бэкенд Hono, фронт Vite + React.',
      en: 'Self-hosted loyalty & inventory platform for small business (cafés, salons, barbershops). Cashback tiers, QR transactions, warehouse, analytics, white-label — data on your own server, no subscriptions. Turborepo monorepo, Hono backend, Vite + React frontend.',
    },
    tag: { ru: 'Проект', en: 'Project' },
    kind: 'project',
    status: 'production',
    role: { ru: 'Fullstack Dev', en: 'Fullstack Dev' },
    note: { ru: 'в проде', en: 'in production' },
    url: 'https://self-loyalty.ru',
    stack: ['Vite + React', 'Hono', 'Prisma', 'Turborepo'],
  },
  {
    id: 'now',
    date: { ru: '2026', en: '2026' },
    year: 2026,
    title: { ru: 'Сейчас', en: 'Now' },
    description: {
      ru: 'Ищу команду, где можно расти как фуллстек и брать ответственность за архитектуру. Пилю pet-проекты, изучаю edge-runtime и WebRTC глубже.',
      en: 'Looking for a team where I can grow as fullstack and own architecture. Building pet projects, going deeper into edge runtime and WebRTC.',
    },
    tag: { ru: 'Open', en: 'Open' },
    kind: 'milestone',
    status: 'in-progress',
    role: { ru: 'Open to work', en: 'Open to work' },
    note: { ru: 'ищу команду', en: 'looking for a team' },
    stack: ['Edge Runtime', 'WebRTC', 'tRPC'],
  },
];

/** Заголовки годов для timeline: крупная цифра, курсивный подзаголовок, сводка. */
export const TIMELINE_YEARS: TimelineYear[] = [
  {
    year: 2024,
    subtitle: { ru: 'первый прод, первые шишки', en: 'first prod, first lessons' },
    summary: {
      ru: 'Первая строка кода в проде. Next.js и NestJS из пет-проектов переросли в реальные задачи — и я пошёл в фуллстек.',
      en: 'First line of code in production. Next.js and NestJS grew from pet projects into real work — and I went fullstack.',
    },
  },
  {
    year: 2025,
    subtitle: { ru: 'production everywhere, mods for fun', en: 'production everywhere, mods for fun' },
    summary: {
      ru: 'Лендинг Leepy и e-commerce Lisavi с нуля, инфраструктура и DevOps, ИСТОК для МФТИ, видеосвязь Пифагорума, MVP стартапа Exploo. Починил заброшенный CS2-мод — 100k+ скачиваний.',
      en: 'The Leepy landing and Lisavi e-commerce from scratch, infrastructure and DevOps, ИСТОК for MIPT, Pifagorum video, the Exploo MVP push. Fixed an abandoned CS2 mod — 100k+ downloads.',
    },
  },
  {
    year: 2026,
    subtitle: { ru: 'shipping & open to work', en: 'shipping & open to work' },
    summary: {
      ru: 'Запустил Lofty — self-hosted лояльность и учёт для малого бизнеса. Ищу команду, где можно расти как фуллстек и брать ответственность за архитектуру.',
      en: 'Shipped Lofty — self-hosted loyalty and inventory for small business. Looking for a team where I can grow as fullstack and own the architecture.',
    },
  },
];

export const PROJECTS: Project[] = [
  {
    id: 'pifagorum',
    num: '01',
    name: 'Пифагорум',
    url: 'https://vc.pifagorum.qque-dev.ru/',
    description: {
      ru: 'LMS-платформа. Самостоятельно спроектировал и поднял модуль видеоконференций на LiveKit — от медиасервера до кастомного UI.',
      en: 'LMS platform. Built the video-conference module on LiveKit end-to-end — from media server to custom UI.',
    },
    stack: [
      { label: 'NestJS' },
      { label: 'Next.js' },
      { label: 'GraphQL' },
      { label: 'Prisma' },
      { label: 'LiveKit', highlight: true },
      { label: 'tldraw' },
    ],
  },
  {
    id: 'istok',
    num: '02',
    name: 'ИСТОК',
    url: 'https://istok-demo.ru/',
    description: {
      ru: 'Платформа языкового тестирования для МФТИ. Автопроверка через GigaChat с кастомным промптом. 10 000+ тестов.',
      en: 'Language testing platform for MIPT. Auto-grading via GigaChat with a custom prompt. 10,000+ tests.',
    },
    stack: [
      { label: 'NestJS' },
      { label: 'Next.js' },
      { label: 'GigaChat', highlight: true },
      { label: 'GigaChain', highlight: true },
      { label: 'Prisma' },
    ],
  },
  {
    id: 'lisavi',
    num: '03',
    name: 'Лисави',
    url: 'https://lisavi.ru/',
    description: {
      ru: 'E-commerce с нуля. ЮКасса, Т-Банк, доставка, промокоды, сертификаты, кастомная админка.',
      en: 'E-commerce from scratch. ЮKassa, T-Bank, shipping, promo codes, gift certificates, custom admin.',
    },
    stack: [
      { label: 'NestJS' },
      { label: 'Next.js' },
      { label: 'Prisma' },
      { label: 'ЮКасса', highlight: true },
      { label: 'Т-Банк', highlight: true },
    ],
  },
  {
    id: 'exploo',
    num: '04',
    name: 'Exploo',
    url: 'https://exploo.ru',
    description: {
      ru: 'Стартап для репетиторов. LiveKit видеосвязь и Better Auth с привязкой Telegram.',
      en: 'Tutoring startup. LiveKit video and Better Auth with Telegram binding.',
    },
    stack: [
      { label: 'React' },
      { label: 'TanStack' },
      { label: 'Hono' },
      { label: 'tRPC' },
      { label: 'LiveKit', highlight: true },
      { label: 'Better Auth' },
    ],
  },
  {
    id: 'leepy',
    num: '05',
    name: 'Leepy',
    url: 'https://leepy.ru/',
    wide: true,
    description: {
      ru: 'Лендинг для дизайнера с CMS на Strapi и анимациями на Framer Motion.',
      en: 'Designer landing with Strapi CMS and Framer Motion animations.',
    },
    stack: [
      { label: 'Next.js' },
      { label: 'Framer Motion', highlight: true },
      { label: 'Strapi' },
    ],
  },
];

export const STACK: StackCategory[] = [
  {
    id: 'frontend',
    label: { ru: 'Frontend', en: 'Frontend' },
    items: [
      { name: 'React', icon: 'react', description: { ru: 'Основной UI-фреймворк', en: 'Main UI framework' } },
      { name: 'Next.js', icon: 'next', description: { ru: 'SSR/SSG/API-роуты', en: 'SSR/SSG/API routes' } },
      { name: 'TypeScript', icon: 'typescript', description: { ru: 'Типы — это любовь', en: 'Types are love' } },
      { name: 'TanStack', icon: 'layers', description: { ru: 'Query, Router, Table', en: 'Query, Router, Table' } },
      { name: 'Tailwind', icon: 'wind', description: { ru: 'Utility-first стили', en: 'Utility-first styling' } },
      { name: 'Framer Motion', icon: 'sparkles', description: { ru: 'Анимации и interactions', en: 'Animations & interactions' } },
      { name: 'tldraw', icon: 'pencil', description: { ru: 'Whiteboard в браузере', en: 'In-browser whiteboard' } },
      { name: 'LiveKit', icon: 'video', description: { ru: 'WebRTC видео/аудио', en: 'WebRTC video/audio' } },
    ],
  },
  {
    id: 'backend',
    label: { ru: 'Backend', en: 'Backend' },
    items: [
      { name: 'NestJS', icon: 'server', description: { ru: 'Любимый Node-фреймворк', en: 'Favorite Node framework' } },
      { name: 'Hono', icon: 'flame', description: { ru: 'Edge-ready, быстрый', en: 'Edge-ready, fast' } },
      { name: 'tRPC', icon: 'plug', description: { ru: 'Типы от бэка к фронту', en: 'End-to-end types' } },
      { name: 'GraphQL', icon: 'network', description: { ru: 'Гибкие запросы', en: 'Flexible queries' } },
      { name: 'Prisma', icon: 'database', description: { ru: 'ORM для Postgres', en: 'ORM for Postgres' } },
      { name: 'PostgreSQL', icon: 'hard-drive', description: { ru: 'Основная БД', en: 'Primary DB' } },
      { name: 'Redis', icon: 'zap', description: { ru: 'Кеш и очереди', en: 'Cache & queues' } },
      { name: 'Better Auth', icon: 'shield', description: { ru: 'Auth с Telegram', en: 'Auth with Telegram' } },
    ],
  },
  {
    id: 'devops',
    label: { ru: 'DevOps', en: 'DevOps' },
    items: [
      { name: 'Docker', icon: 'box', description: { ru: 'Контейнеризация', en: 'Containerization' } },
      { name: 'Nginx', icon: 'split', description: { ru: 'Reverse proxy', en: 'Reverse proxy' } },
      { name: 'GitHub Actions', icon: 'workflow', description: { ru: 'CI/CD пайплайны', en: 'CI/CD pipelines' } },
      { name: 'VPS / Linux', icon: 'terminal', description: { ru: 'Boot, ssh, systemd', en: 'Boot, ssh, systemd' } },
    ],
  },
  {
    id: 'tools',
    label: { ru: 'Tools', en: 'Tools' },
    items: [
      { name: 'Git', icon: 'git-branch', description: { ru: 'Rebase > merge', en: 'Rebase > merge' } },
      { name: 'Figma', icon: 'figma', description: { ru: 'Читаю макеты', en: 'Reading designs' } },
      { name: 'VS Code', icon: 'code', description: { ru: 'Основной редактор', en: 'Main editor' } },
      { name: 'Postman', icon: 'send', description: { ru: 'API debugging', en: 'API debugging' } },
      { name: 'Notion', icon: 'notebook', description: { ru: 'Заметки и доки', en: 'Notes & docs' } },
      { name: 'Telegram', icon: 'message-circle', description: { ru: 'Связь с командой', en: 'Team comms' } },
    ],
  },
];
